# Generated by Django 2.1.5 on 2019-01-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190105_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
